FROM mealplanning-base

# Set the working directory (if not already set in the base image)
WORKDIR /app

# Copy the service-specific code
COPY data_processor.py .
COPY requirements_data_processor.txt .
COPY food_list.txt .

RUN pip install --no-cache-dir -r requirements_data_processor.txt

# Set the container’s entrypoint to run your script
ENTRYPOINT [ "python", "data_processor.py" ]
