services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=meal_planning
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    # to make pgAdmin configuration persistent, create a folder data_pgadmin and mount it to the /var/lib/pgadmin folder:
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin      
    ports:
      - "8080:80"
    networks:
      - pg-network

  meal_ingest:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pgdatabase
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=pgdatabase
      - DB_PORT=5432
      - DB_NAME=meal_planning
      - TABLE_NAME=recipes
      - REPO_URL=https://github.com/Matt1303/recipe_html_pages
      - CLONE_DIR=/app/clone_dir
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

# defines a named volume called pgdata. The pgdatabase service uses this volume to store its data at /var/lib/postgresql/data
volumes:
  pgdata: